# Generated by Django 2.0.3 on 2018-04-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180407_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='names',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='ordinances',
            field=models.IntegerField(default=0),
        ),
    ]
