# Generated by Django 2.0.3 on 2018-04-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20180407_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='names',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='ordinances',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
